# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestchatbotemojifile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testchatbotemojifile(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 840)
    self.driver.switch_to.frame(7)
    self.driver.find_element(By.CSS_SELECTOR, ".exw-open-launcher__container").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(6)
    self.driver.find_element(By.CSS_SELECTOR, ".exw-add-emoji").click()
    self.driver.find_element(By.CSS_SELECTOR, "emoji-picker").click()
    element = self.driver.find_element(By.LINK_TEXT, "We run on Exairon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".exw-add-file path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".exw-drag-drop-select-button").click()
  
