# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestchatbotmessage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testchatbotmessage(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 840)
    self.driver.switch_to.frame(8)
    self.driver.find_element(By.CSS_SELECTOR, ".exw-open-launcher__container").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(7)
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("pair2 tobeto")
    self.driver.find_element(By.CSS_SELECTOR, "svg:nth-child(2) > path:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".exw-response:nth-child(1) .exw-sender-response").text == "Memnun oldum pair2 tobeto, Sana hangi konuda yardımcı olmamı istersin?"
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".exw-reply:nth-child(1)")))
    self.driver.find_element(By.CSS_SELECTOR, ".exw-reply:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "strong:nth-child(1)").text == "üniversite öğrencileri, profesyoneller, işini/mesleğini"
    assert self.driver.find_element(By.CSS_SELECTOR, ".exw-group-message:nth-child(5) > .exw-message:nth-child(2) p").text == "Tobeto’da ihtiyaçların ve kaynaklarına göre öğrenim yolculuğunu sen tasarlarsın. Tobeto değerlendirme araçlarıyla kendini test edebilirsin."
    assert self.driver.find_element(By.CSS_SELECTOR, ".exw-message:nth-child(3) .exw-sender-response").text == "Bunları da merak ediyor olabilirsiniz. 👀"
  
