# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestemptylogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testemptylogin(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("aa")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("aa")
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(4)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    self.driver.find_element(By.ID, "recaptcha-verify-button").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".mt-4").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".toast-body").text == "• Geçersiz e-posta veya şifre."
    self.driver.find_element(By.NAME, "email").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").text == "Doldurulması zorunlu alan*"
    self.driver.find_element(By.NAME, "password").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "form > p").text == "Doldurulması zorunlu alan*"
  
