# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestinvalidphone():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testinvalidphone(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".signup").click()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("pair2")
    self.driver.find_element(By.NAME, "lastName").send_keys("tobeto")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("pair2tobeto2@gmail.com")
    element = self.driver.find_element(By.NAME, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.NAME, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.NAME, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-input-group:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,191.1999969482422)")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("pair2tobeto2")
    self.driver.find_element(By.NAME, "passwordAgain").click()
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("pair2tobeto2")
    self.driver.find_element(By.CSS_SELECTOR, ".mt-4").click()
    self.driver.find_element(By.NAME, "contact").click()
    self.driver.find_element(By.NAME, "membershipContrat").click()
    self.driver.find_element(By.NAME, "emailConfirmation").click()
    self.driver.find_element(By.NAME, "phoneConfirmation").click()
    element = self.driver.find_element(By.NAME, "phoneConfirmation")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 123")
    self.driver.switch_to.frame(9)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-yes").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-yes")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").text == "En az 10 karakter girmelisiniz."
    self.driver.find_element(By.ID, "phoneNumber").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").text == "Doldurulması zorunlu alan*"
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 00000000000000")
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").text == "En fazla 10 karakter girebilirsiniz."
  
