# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsuccessfulregister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsuccessfulregister(self):
    self.driver.get("https://tobeto.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Giriş Yap").click()
    self.driver.find_element(By.CSS_SELECTOR, ".signup").click()
    self.driver.execute_script("window.scrollTo(0,185.60000610351562)")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "firstName")))
    self.driver.find_element(By.NAME, "firstName").send_keys("pair2")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "lastName")))
    self.driver.find_element(By.NAME, "lastName").send_keys("tobeto")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "email")))
    self.driver.find_element(By.NAME, "email").send_keys("tobeto.pair2@gmail.com")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "password")))
    self.driver.find_element(By.NAME, "password").send_keys("tobeto.pair2tobeto")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "passwordAgain")))
    self.driver.find_element(By.NAME, "passwordAgain").send_keys("tobeto.pair2tobeto")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".mt-4")))
    self.driver.find_element(By.CSS_SELECTOR, ".mt-4").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "contact")))
    self.driver.find_element(By.NAME, "contact").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "membershipContrat")))
    self.driver.find_element(By.NAME, "membershipContrat").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "emailConfirmation")))
    self.driver.find_element(By.NAME, "emailConfirmation").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "phoneConfirmation")))
    self.driver.find_element(By.NAME, "phoneConfirmation").click()
    element = self.driver.find_element(By.NAME, "phoneConfirmation")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "phoneNumber").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "phoneNumber")))
    self.driver.find_element(By.ID, "phoneNumber").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("+90 534 608 50 95")
    self.driver.switch_to.frame(9)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".recaptcha-checkbox-border")))
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn-yes")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-yes").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".checkout-bg").text == "Tobeto Platform\\\'a kaydınız başarıyla gerçekleşti.\\\\nGiriş yapabilmek için e-posta adresinize iletilen doğrulama linkine tıklayarak hesabınızı aktifleştirin.\\\\nGiriş Yap"
  
