# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestchatbotchatend():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testchatbotchatend(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 840)
    self.driver.switch_to.frame(7)
    self.driver.find_element(By.CSS_SELECTOR, ".exw-open-launcher__container").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(6)
    self.driver.find_element(By.CSS_SELECTOR, ".exw-end-session-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".finishSessionCheckButtons > button:nth-child(1)").click()
    self.driver.find_element(By.ID, "surveyTextArea").click()
    self.driver.find_element(By.ID, "surveyTextArea").send_keys("Teşekkürler")
    self.driver.find_element(By.ID, "surveyBtn").click()
  
